### ISSUE TITLE
TabBar colors doesn't match theme

### ISSUE THREAD

**Issue by tp-rbrasset** [Mohamed-512/Extra-Streamlit-Components#45] opened 2023-06-22 02:51 UTC
I tried to use custom streamlit theme while using the TabBar and it seems to not work. 

When inspecting with the chrome web tool, it seems that the bootstrap.min.css defines and apply the --stremlit-primary-color as the color of the TabBar.

Is it a bug or am I doing something wrong?

**Comment by tp-rbrasset** [comment] 2023-06-28 18:05
Anyone?

**Comment by elijahnicpon** [comment] 2023-07-06 14:54
I came across this as well. Looks like there is an open PR, #37, that solves this issue (along with a similar issue with BoundingImage and StepperBar, by changing `--stremlit-primary-color` to `--primary-color` in the css). @Mohamed-512 would you mind merging this one? Thank you!!

**Comment by tp-rbrasset** [comment] 2023-07-11 21:43
@elijahnicpon Thank you for the information. Can't wait for the PR to be merged!

**Comment by Mohamed-512** [comment] 2024-02-17 14:58
Fixed in version 0.1.70

**Closed by Mohamed-512** 2024-02-17 14:58 UTC

**Comment by alex-milanovic** [comment] 2024-06-06 10:58
It seems these changes are not applied in 0.1.70 or 0.1.71 in the PyPI build? I'm also trying to build from source to get these changes in

**Comment by benlindsay** [comment] 2024-06-11 14:24
Confirmed, tab_bar isn't respecting the primary color for me with version 0.1.70 either

**Comment by fdurant** [comment] 2025-01-03 14:28
Same here

**Comment by emib95** [comment] 2025-05-02 09:41
same for me in 0.1.80
